### ISSUE TITLE
No options for port settings

### ISSUE THREAD

**Issue by brendonlecomte** [mbedded-ninja/NinjaTerm#64] opened 2015-10-12 20:22 UTC
Drop down lists have no values for # of data bits, partiy, or stop bits. 
Can't enter numbers manually either. 
So can't open a port.

**Comment by gbmhunter** [comment] 2015-10-12 20:24
Duplicate of #19 .
Default values for these are automatically selected a.t.m (8n1).

**Closed by gbmhunter** 2015-10-12 20:24 UTC
